"""add expenses table

Revision ID: f18c7f08b049
Revises:
Create Date: 2026-09-20 09:37:11.416463

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f18c7f08b049'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_expenses_amount_positive'),
    sa.CheckConstraint('char_length(trim(description)) > 0', name='ck_expenses_description_not_blank'),
    sa.CheckConstraint('char_length(trim(merchant)) > 0', name='ck_expenses_merchant_not_blank'),
    sa.CheckConstraint('scale(amount) <= 2', name='ck_expenses_amount_max_two_decimal_places'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
